language: ruby

os:
  - osx

osx_image: xcode8.3

cache:
  directories:
    # Cache homebrew and everything it installs.
    - "/usr/local"

before_install:
  - brew ls --versions coreutils >/dev/null || brew install coreutils
  - brew ls --versions wget >/dev/null || brew install wget
  - brew ls --versions cmake >/dev/null || brew install cmake
  - brew ls --versions libtool >/dev/null || brew install libtool
  - brew ls --versions go >/dev/null || brew install go
  - brew ls --versions bazel >/dev/null || brew install bazel
  - |
    if [ "${PULL_REQUEST}" = "true" -a -n "${PULL_REQUEST_REPO}" -a -n "${PULL_REQUEST_SHA}" ]; then
      git branch -D ci-branch || true
      git remote remove pr_repo || true
      git remote add pr_repo "https://github.com/${PULL_REQUEST_REPO}.git"
      git fetch pr_repo
      git checkout -b ci-branch
      git merge --no-edit "${PULL_REQUEST_SHA}"
    fi

script:
  # set up bazelrc
  - |
      (echo "build --curses=no --show_task_finish" &&
       echo "test --curses=no --show_task_finish") >~/.bazelrc
  # bazel uses jgit internally and the default circle-ci .gitconfig says to
  # convert https://github.com to ssh://git@github.com, which jgit does not support.
  - mv ~/.gitconfig ~/.gitconfig_save
  - bazel build --verbose_failures //source/...
  - bazel build --verbose_failures //test/...
  - bazel test --test_output=all //test/...

# notifications:
#   webhooks: https://webhooks.turbinelabs.net/v1/build/webhook

